#!/bin/sh -ex

NAME=symfony
DB_PASS=$(mcookie)

WEBROOT=/var/www/symfony
LOCAL_SRC=/usr/local/src

# Version of symfony to install
SYMFONY_VERSION=4.3

# php tweaks
PHPINI1=/etc/php/7.2/apache2/php.ini
PHPINI2=/etc/php/7.2/cli/php.ini

# Set timezone (TODO: we should move this to an inithook)
sed -i "s|^;date.timezone\(.*\)|date.timezone = 'America/Los_Angeles'|" $PHPINI1
sed -i "s|^;date.timezone\(.*\)|date.timezone = 'America/Los_Angeles'|" $PHPINI2

# Set open tag to off for php
sed -i "s|^short_open_tag = On|short_open_tag = Off|" $PHPINI1
sed -i "s|^short_open_tag = On|short_open_tag = Off|" $PHPINI2

# Up the memory from  32MB to 64MB (Issues with clear:cache command)
sed -i "s|^memory_limit = 32M|memory_limit = 128M|" $PHPINI1
sed -i "s|^memory_limit = 32M|memory_limit = 128M|" $PHPINI2


# start mysql server
service mysql start

# create symfony database and user
mysql --user=root --password=$MYSQL_PASS --batch --execute "\
CREATE DATABASE $NAME; \
GRANT ALL PRIVILEGES ON $NAME.* TO $NAME@localhost IDENTIFIED BY '$DB_PASS'; \
FLUSH PRIVILEGES;"

# install 3.4.x LTS symfony
#composer create-project symfony/symfony-demo /var/www/symfony-demo
composer create-project symfony/website-skeleton $WEBROOT

# Change owner to root
chown root:root -R $WEBROOT


# Set permissions so that cache and logs can be updated by apache2 user
chown -R www-data:www-data $WEBROOT/var

# update .htaccess -  setup app_dev as default
HTACCESS=$WEBROOT/public/.htaccess

cat > $HTACCESS <<EOF
# Use the front controller as index file. It serves as a fallback solution when
# every other rewrite/redirect fails (e.g. in an aliased environment without
# mod_rewrite). Additionally, this reduces the matching process for the
# start page (path "/") because otherwise Apache will apply the rewriting rules
# to each configured DirectoryIndex file (e.g. index.php, index.html, index.pl).
DirectoryIndex index.php

# By default, Apache does not evaluate symbolic links if you did not enable this
# feature in your server configuration. Uncomment the following line if you
# install assets as symlinks or if you experience problems related to symlinks
# when compiling LESS/Sass/CoffeScript assets.
# Options FollowSymlinks

# Disabling MultiViews prevents unwanted negotiation, e.g. "/index" should not resolve
# to the front controller "/index.php" but be rewritten to "/index.php/index".
<IfModule mod_negotiation.c>
    Options -MultiViews
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine On

    # Determine the RewriteBase automatically and set it as environment variable.
    # If you are using Apache aliases to do mass virtual hosting or installed the
    # project in a subdirectory, the base path will be prepended to allow proper
    # resolution of the index.php file and to redirect to the correct URI. It will
    # work in environments without path prefix as well, providing a safe, one-size
    # fits all solution. But as you do not need it in this case, you can comment
    # the following 2 lines to eliminate the overhead.
    RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]

    # Sets the HTTP_AUTHORIZATION header removed by Apache
    RewriteCond %{HTTP:Authorization} .
    RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect to URI without front controller to prevent duplicate content
    # (with and without `/index.php`). Only do this redirect on the initial
    # rewrite by Apache and not on subsequent cycles. Otherwise we would get an
    # endless redirect loop (request -> rewrite to front controller ->
    # redirect -> request -> ...).
    # So in case you get a "too many redirects" error or you always get redirected
    # to the start page because your Apache does not expose the REDIRECT_STATUS
    # environment variable, you have 2 choices:
    # - disable this feature by commenting the following 2 lines or
    # - use Apache >= 2.3.9 and replace all L flags by END flags and remove the
    #   following RewriteCond (best solution)
    RewriteCond %{ENV:REDIRECT_STATUS} ^$
    RewriteRule ^index\.php(?:/(.*)|$) %{ENV:BASE}/$1 [R=301,L]

    # If the requested filename exists, simply serve it.
    # We only want to let Apache serve files and not directories.
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule ^ - [L]

    # Rewrite all other queries to the front controller.
    RewriteRule ^ %{ENV:BASE}/index.php [L]
</IfModule>

<IfModule !mod_rewrite.c>
    <IfModule mod_alias.c>
        # When mod_rewrite is not available, we instruct a temporary redirect of
        # the start page to the front controller explicitly so that the website
        # and the generated links can still be used.
        RedirectMatch 307 ^/$ /index.php/
        # RedirectTemp cannot be used instead
    </IfModule>
</IfModule>
EOF


# Update default twig template (Give it a TKL Branding)
TEMPLATE=$WEBROOT/templates/base.html.twig

# update welcome template, part 1 - Welcome
# Adds TurnKey Linux to the welcome
sed -i "s|<h1>\(.*\)</h1>|<h1>Welcome to TurnKey Symfony 4.3</h1>|" $TEMPLATE

# update welcome template, part 2 - Whats next
# Use SED to find the whats next text inside the twig file
# then we insert multi line html into it
#sed -i "s|<h2>What's next?</h2>| \n\
#                <h2>What do I do now?</h2>\n\
#                        <p>This welcome page is being served via index.php</p> \n\
#                        <p>You should secure it by specifying your IP address in <i>$APPDEV</i></p> \n\
#                        <p>When ready for production, update <i>$HTACCESS</i> to specify app.php instead.</p> \n\
#                        <p><i>Note: The database configuration is already setup for you, enjoy!</i></p> \n\
#|" $TEMPLATE



# configure apache
a2dissite 000-default
a2ensite symfony
a2enmod rewrite


# stop mysql
service mysql stop

